const constants = {
  SET_WINDOW: "SET_WINDOW",
  SET_VOT_YOUTUBE_CHANNEL_DATA: "SET_VOT_YOUTUBE_CHANNEL_DATA",
  SET_VR_YOUTUBE_CHANNEL_DATA: "SET_VR_YOUTUBE_CHANNEL_DATA",
  SET_ALL_VR_YOUTUBE_CHANNEL_DATA: "SET_ALL_VR_YOUTUBE_CHANNEL_DATA",
  GET_YOUTUBE_CHANNEL_DATA: "GET_YOUTUBE_CHANNEL_DATA",
  SET_VIDEO_TO_WATCH: " SET_VIDEO_TO_WATCH",
  SET_GUILD_MEMBERS: "SET_GUILD_MEMBERS",
  GET_GUILD_MEMBERS: "GET_GUILD_MEMBERS",
  SET_EDITOR_STATE: "SET_EDITOR_STATE"
 }
 export default constants