const constants = {
  SET_WINDOW: "SET_WINDOW",
  GET_VOT_YOUTUBE_CHANNEL_DATA: "GET_VOT_YOUTUBE_CHANNEL_DATA",
  GET_VR_YOUTUBE_CHANNEL_DATA: "GET_VR_YOUTUBE_CHANNEL_DATA",
  GET_ALL_VR_YOUTUBE_CHANNEL_DATA: "GET_ALL_VR_YOUTUBE_CHANNEL_DATA",
  GET_YOUTUBE_CHANNEL_DATA: "GET_YOUTUBE_CHANNEL_DATA",
  SET_VIDEO_TO_WATCH: " SET_VIDEO_TO_WATCH",
  GET_GUILD_MEMBERS: "GET_GUILD_MEMBERS",
  GET_GUILD_MEMBERS: "GET_GUILD_MEMBERS",
  SET_EDITOR_STATE: "SET_EDITOR_STATE",
  GET_ARTICLE_STATE: "GET_ARTICLE_STATE",
  SET_LOGIN_TOKEN: "SET_LOGIN_TOKEN",
  SET_LOGOUT: "SET_LOGOUT"
 }
 export default constants