const constants = {
  SET_WINDOW: "SET_WINDOW",
  GET_VOT_YOUTUBE_CHANNEL_DATA: "GET_VOT_YOUTUBE_CHANNEL_DATA",
  GET_VR_YOUTUBE_CHANNEL_DATA: "GET_VR_YOUTUBE_CHANNEL_DATA",
  GET_ALL_VR_YOUTUBE_CHANNEL_DATA: "GET_ALL_VR_YOUTUBE_CHANNEL_DATA",
  GET_YOUTUBE_CHANNEL_DATA: "GET_YOUTUBE_CHANNEL_DATA",
  SET_VIDEO_TO_WATCH: " SET_VIDEO_TO_WATCH",
  GET_GUILD_MEMBERS: "GET_GUILD_MEMBERS",
  GET_GUILD_MEMBERS: "GET_GUILD_MEMBERS",
  SET_EDITOR_STATE: "SET_EDITOR_STATE",
  GET_ARTICLES: "GET_ARTICLES",
  GET_NEWSLETTERS: "GET_NEWSLETTERS",
  GET_HTML_DOCUMENT: "GET_HTML_DOCUMENT",
  CLEAR_HTML_DOCUMENT: "CLEAR_HTML_DOCUMENT",
  SET_LOGIN_TOKEN: "SET_LOGIN_TOKEN",
  SET_API_RESPONSE: "SET_API_RESPONSE",
  CLEAR_API_RESPONSE: "CLEAR_API_RESPONSE",
  SET_LOGOUT: "SET_LOGOUT",
  GET_USERS: "GET_USERS"
 }
 export default constants